### ISSUE TITLE
Not working with Next.js v12

### ISSUE THREAD

**Issue by shokhboz-abdullaev** [nanxiaobei/solid-react#2]
Hi! First of all, I want to thank you for bringing true reactivity to React.

Let's then get to the issue:

It's my first time using solid-react with Next.js, but I thought it would work even if React version is v18 (looking into package.json of the solid-react). 

The first issue is that `useUpdate()` is not reacting to updates inside the component. The second issue is that `useSignal()`'s setter function is not setting the state within `onMount()` or even React's `useEffect()`. 

I will be waiting for the response, would like to hear about the issue is resolved. 

Thanks in advance.

**Comment by shokhboz-abdullaev** [comment]
Just a quick update: to reproduce the issue you can use the `useSignal()` hook and set a value in `useMount()`. The update will not trigger render in the template.

**Comment by shokhboz-abdullaev** [comment]
Another issue is that if using reactive variables (`value()`) with string concatenation or template literals the output in the for instance `className` will be `[object Object]`.

**Comment by nanxiaobei** [comment]
Thanks for your feedback~

1. Not tested in Next.js. At present, it is not clear what the specific problem is, maybe a reproducible demo is needed.
2. Yes, there may be problems with `value()` and some edge cases may need to be handled.
3. This is an experimental project, which may not have a lot of time to support. If you can provide a reproducible demo, I can try to check, but it can't guarantee to cover all the existing scenes.
