### ISSUE TITLE
I have a little problem with the code.

### ISSUE THREAD

**Issue by Luncher** [nanxiaobei/solid-react#3]
First of all, the idea of this project is very nice. I have a few questions I would like to ask:

1. https://github.com/nanxiaobei/solid-react/blob/65688c934664420170fa3576d13b2a1f5e47363f/src/index.tsx#L63-L70

I don't know what is the meaning of this hooks existence.

2.  I'm not quite sure what this `arrIndex` does.

`useUpdate` arrIndex: https://github.com/nanxiaobei/solid-react/blob/65688c934664420170fa3576d13b2a1f5e47363f/src/index.tsx#L176

`useAuto`: arrIndex: https://github.com/nanxiaobei/solid-react/blob/65688c934664420170fa3576d13b2a1f5e47363f/src/index.tsx#L197

From the source code, it seems that the only difference is the timing of their calls.

3.  useSignal vs proxy

I see that `useSignal` uses a proxy to handle `non-Primitive` types. But I didn't see a specific demo. I don't know what the specific scene is, what can I refer to?

4. batch update vs setTimeout

I saw that the `runFlows` function is followed by a `setTimeout` after calling `batch processing`. Can you tell me what is the effect of this?

thanks.

**Comment by nanxiaobei** [comment]
1. with `StrictMode`, `useEffect` will run twice, so use `isFirst` flag to make `runFlows` only run once(not a good way but no other solutions).
2. `arrIndex` is this item's parent "set"'s `index` in the `flowSetArr`(`[set, set, set]`).
3. if without `proxy`, data in JSX like `obj.a` or `arr.map()` will not work, only primitive data like `123` or `"abc"` will work.
4. `runFlows` will run several times in a "re-render" cycle, so use `setTimeout` to do the "clear" when a re-render cycle is done.

**Comment by Luncher** [comment]
>arrIndex is this item's parent "set"'s index in the flowSetArr([set, set, set]).

It seems that the third set element of the array is not used.

>if without proxy, data in JSX like obj.a or arr.map() will not work, only primitive data like 123 or "abc" will work.

```typescript
function App() {
  const [getObj, setObj] = useSignal({ foo: { bar: 1 }})
  return <Children obj={getObj()} />
}

function Children({ obj }) {
  return <Nested bar={obj.foo} />
}

function Nested({ foo }) {
  return <span>{foo.bar}</span>
}
```
According to my understanding, are you talking about such a scene?


>runFlows will run several times in a "re-render" cycle, so use setTimeout to do the "clear" when a re-render cycle is done.

How to confirm that when setTimeout is called, the re render cycle is done. Do you have any related instructions？

thanks.
