### ISSUE TITLE
同步输出,第二次的时候会跟第一次一样

### ISSUE THREAD

**Issue by Qingzii** [nanxiaobei/solid-react#4]
![image_2023-09-01_20-18-25](https://github.com/nanxiaobei/solid-react/assets/59027764/94df2190-734e-4eca-abc3-67781bd7c363)
![image_2023-09-01_20-18-54](https://github.com/nanxiaobei/solid-react/assets/59027764/4dfbdcbf-5e35-4626-9458-5ec56ce28f21)

**Comment by nanxiaobei** [comment]
`1.1.0` 中已修复。
