### ISSUE TITLE
count()无法进行数据操作

### ISSUE THREAD

**Issue by lsbFlying** [nanxiaobei/solid-react#6]
count()事实上返回的是一个组件，它无法进行正常的数据操作，该如何解决这个问题，我最近也在尝试类似的效果遇到这种问题，目前还没有解决思路，有点头疼
`
return (
  <>
    {count() > 1 ? "text" : "none"}
  </>
);
`

**Comment by nanxiaobei** [comment]
API 最后一个 `Run()`

```jsx
import { Run } from 'solid-react';

<div>{Run(count() > 1 ? 'text' : 'none')}</div>;
```

https://github.com/nanxiaobei/solid-react?tab=readme-ov-file#run
